steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag'
  - 'us-central1-docker.pkg.dev/playground-s-11-87d70c32/my-app-repo/ai-study-buddy'
  - '--build-arg'
  - 'VITE_GEMINI_API_KEY=${_GEMINI_API_KEY}'
  - '.'
images:
- 'us-central1-docker.pkg.dev/playground-s-11-87d70c32/my-app-repo/ai-study-buddy'
substitutions:
  _GEMINI_API_KEY: ''
